micronaut:
  application:
    name: cinema-reservation

datasources:
  default:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: postgres

flyway:
  datasources:
    default:
      locations: classpath:db_migrations


